//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapos_Restaurante_VCliente_Pruebas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELEMENTOS()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int IdElemento { get; set; }
        public int Categoria { get; set; }
        public string NombreElemento { get; set; }
        public string Descripcion { get; set; }
        public string ImagenElementoURL { get; set; }
        public double Precio { get; set; }
    
        public virtual CATEGORIAS CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
