//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapos_Restaurante_VCliente_Pruebas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int IdComanda { get; set; }
        public int IdElemento { get; set; }
        public int CantidadElementos { get; set; }
    
        public virtual COMANDAS COMANDAS { get; set; }
        public virtual ELEMENTOS ELEMENTOS { get; set; }
    }
}
